import {
  ClerkProvider,
} from "@clerk/nextjs";

import "./globals.css";
import { Sniglet  } from 'next/font/google';


const font = Sniglet({
  weight: ['400'],
  subsets: ['latin']
});


export const metadata = {
  title: "Courzo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${font.className}`}
        >
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
